### ISSUE TITLE
Unable to program Attiny through Arduino as ISP

### ISSUE THREAD

**Issue by hennenzac** [gepd/Deviot#93]
My problem is very similar to issue #40.  I am able to program the Attiny through the Arduino using the Arduino IDE.  I then programmed the Arduino alone using Deviot to see if I had that working, which was successful. So my setup should be correct.  I'm not sure what else to try.

 Here is the information in the console when I upload.

[consoleoutput.txt](https://github.com/gepd/Deviot/files/638662/consoleoutput.txt)

**Comment by gepd** [comment]
In your output file, this line said the port cannot be find

`avrdude: ser_open(): can't open device "\\.\com1": The system cannot find the file specified.`

are you sure that is right port? 
Or may be the port may be in use by another program

**Comment by hennenzac** [comment]
I saw that as well.  The Arduino is hooked up to COM4, which is what I chose in the Deviot menu/Serial ports.  At the top of the output file I sent it says Upload port: COM4.  Is there some other setting I need to change?  I have the board and environment set to Generic Attiny 85, Programmer set to Arduino as ISP (which i programmed to be an ISP via the Arduino IDE), and serial port set to COM4.

**Comment by gepd** [comment]
Change the programmer to `None` and try again, it should solve the problem

**Comment by hennenzac** [comment]
I changed it to None, but it still fails with a different error this time.  It says it can't find a USBtiny device.  I programmed the Arduino as ISP through the arduino IDE example, if that offers more info. 


Here is the last bit with the error.

Checking program size
text	   data	    bss	    dec	    hex	filename
1084	      0	      9	   1093	    445	.pioenvs\attiny85\firmware.elf
Building .pioenvs\attiny85\firmware.hex
Looking for upload port...
Uploading .pioenvs\attiny85\firmware.hex
avrdude: Error: Could not find USBtiny device (0x1781/0xc9f)

avrdude done.  Thank you.

*** [upload] Error 1
 [ERROR] Took 4.73 seconds 


 [SUMMARY] 
Environment uno     	[SKIP]
Environment attiny85	[ERROR]
 [ERROR] Took 4.73 seconds )
16:18:38 ERROR | it took 5.52s

**Comment by gepd** [comment]
I've saw this answer about `Error: Could not find USBtiny device (0x1781/0xc9f)` https://stackoverflow.com/a/32944999/3769629 

Can you try pressing the reset button as JanuskaE recommend?

**Comment by hennenzac** [comment]
I am assuming the reset on the Arduino board.  I have tried every combination of this with no change to the output file.

**Comment by gepd** [comment]
can you check if this problem still keeps in deviot 2?
